services:
  webapp:
    image: ${WEBAPP_IMAGE_NAME:-icpac/cgan-ui}
    container_name: ${WEBAPP_CNTR_NAME:-cgan-ui}
    build:
      context: .
      dockerfile: ${WEBAPP_DOCKERFILE:-docker/webapp/Dockerfile}
      args:
        APP_USER_ID: ${APP_USER_ID:-10010}
        APP_GROUP_ID: ${APP_GROUP_ID:-10010}
        WORK_HOME: ${WORK_HOME:-/opt/cgan}
        APP_DIR: ${APP_DIR:-/opt/app}
        DATA_STORE_DIR: ${DATA_STORE_DIR:-/opt/store}
    restart: ${RESTART_POLICY:-always}
    entrypoint: ${APP_DIR:-/opt/app}/entrypoint.sh
    env_file:
      - ${MERCURY_ENV_FILE:-.env}
    depends_on:
      - uidb
    volumes:
      - ${CGAN_DATA_STORE:-./data/store}:${DATA_STORE_DIR:-/opt/store}
      - ${MERCURY_STATIC:-./data/static}:${WORK_HOME:-/opt/cgan}/mercury/django_static
      - ${MERCURY_MEDIA:-./data/media}:${WORK_HOME:-/opt/cgan}/mercury/media

  jobs:
    image: ${JOBS_IMAGE_NAME:-icpac/cgan-jobs}
    container_name: ${JOBS_CNTR_NAME:-data-pipelines}
    build:
      context: .
      dockerfile: ${JOBS_DOCKERFILE:-docker/jobs/Dockerfile}
      args:
        APP_USER_ID: ${APP_USER_ID:-10010}
        APP_GROUP_ID: ${APP_GROUP_ID:-10010}
        WORK_HOME: ${WORK_HOME:-/opt/cgan}
        APP_DIR: ${APP_DIR:-/opt/app}
        DATA_STORE_DIR: ${DATA_STORE_DIR:-/opt/store}
        LOGS_DIR: ${APP_LOGS_DIR:-/opt/logs}
    restart: ${RESTART_POLICY:-always}
    command: ["sh", "entrypoint.sh"]
    environment:
      - DATA_STORE_DIR=${DATA_STORE_DIR:-/opt/store}
      - IFS_SERVER_HOST=${IFS_SERVER_HOST:-domain.example}
      - IFS_SERVER_USER=${IFS_SERVER_USER:-username}
      - IFS_PRIVATE_KEY=${IFS_PRIVATE_KEY:-/srv/ssl/private.key}
    volumes:
      - ${CGAN_DATA_STORE:-./data/store}:${DATA_STORE_DIR:-/opt/store}
      - ${CGAN_LOGS_DIR:-./data/logs}:${APP_LOGS_DIR:-/opt/logs}
      - ${CGAN_MAIN_CONFIG:-./data/configs/main.yaml}:${WORK_HOME:-/opt/cgan}/ensemble-cgan/dsrnngan/confg.yaml:ro
      - ${CGAN_DATA_PATHS_CONFIG:-./data/configs/data_paths.yaml}:${WORK_HOME:-/opt/cgan}/ensemble-cgan/dsrnngan/data_paths.yaml:ro
      - ${CGAN_FORECAST_CONFIG:-./data/configs/forecast.yaml}:${WORK_HOME:-/opt/cgan}/ensemble-cgan/dsrnngan/forecast.yaml:ro
      - ${CGAN_LOCAL_CONFIG:-./data/configs/local.yaml}:${WORK_HOME:-/opt/cgan}/ensemble-cgan/dsrnngan/local_config.yaml:ro
      - ${IFS_SERVER_KEY:-./data/private/id_rsa}:${IFS_PRIVATE_KEY:-/srv/ssl/private.key}:ro

  # jupyter:
  #   image: ${LAB_IMAGE_NAME:-icpac/cgan-jupyter}
  #   container_name: ${LAB_CNTR_NAME:-cgan-jupyter}
  #   build:
  #     context: .
  #     dockerfile: ${JUPYTER_DOCKERFILE:-docker/lab/Dockerfile}
  #     args:
  #       APP_USER_ID: ${LAB_USER_ID:-10010}
  #       APP_GROUP_ID: ${LAB_GROUP_ID:-10010}
  #       WORK_HOME: ${WORK_HOME:-/opt/cgan}
  #       DATA_STORE_DIR: ${DATA_STORE_DIR:-/opt/store}
  #   restart: ${RESTART_POLICY:-always}
  #   command: jupyter-lab --IdentityProvider.token '' --ServerApp.base_url '/model/' --port 8000 --ip 0.0.0.0 --no-browser
  #   volumes:
  #     - ${CGAN_DATA_STORE:-./data/store}:${DATA_STORE_DIR:-/opt/store}
  #     - ./notebooks:${WORK_HOME-/opt/cgan}

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: ${NGINX_IMAGE_NAME:-icpac/mercury-nginx}
    container_name: ${NGINX_CNTR_NAME:-mercury-nginx}
    restart: ${RESTART_POLICY:-always}
    ports:
      - ${WEB_UI_HOST_IP:-172.17.0.1}:${WEB_UI_HOST_PORT:-4050}:80
    volumes:
      - ${MERCURY_STATIC:-./data/static}:/app/mercury/static
      - ${MERCURY_MEDIA:-./data/media}:/app/mercury/media
      - ${CGAN_DATA_STORE:-./data/store}/ecmwf:${PUBLIC_DATA_DIR:-/srv/data}/open-ifs
      - ${CGAN_DATA_STORE:-./data/store}/gbmc:${PUBLIC_DATA_DIR:-/srv/data}/cgan-ifs
      - ${CGAN_DATA_STORE:-./data/store}/cgan:${PUBLIC_DATA_DIR:-/srv/data}/cgan-forecast
    depends_on:
      - webapp
    command: '/bin/sh -c ''nginx -g "daemon off;"'''

  uidb:
    image: postgres:alpine
    container_name: ${UI_DB_CNTR_NAME:-ui-pgdb}
    restart: ${RESTART_POLICY:-always}
    volumes:
      - ${UI_DB_DATA:-./data/pgdata}:/var/lib/postgresql/data/
    ports:
      - ${UI_DB_HOST_IP:-172.17.0.1}:${UI_DB_HOST_PORT:-5420}:5432
    environment:
      - TZ={TZ:-Africa/Nairobi}
      - POSTGRES_DB=${POSTGRES_DB:-cgan_ui_db}
      - POSTGRES_USER=${POSTGRES_USER:-climcast}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-z7ZAWxzUPtmh2qoA}
