[tool.poetry]
name = "cgan_ui"
version = "0.1.0"
description = "cGAN interactive user interface"
authors = ["Jason Kinyua <jaysnmury@gmail.com>"]
license = "CC BY 4.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.13"
mercury = "^2.4.3"
ecmwf-opendata = "^0.3.3"
loguru = "^0.7.2"
schedule = "^1.2.2"
sysrsync = "^1.1.1"
folium = "^0.16.0"
# show_forecasts = {git = "https://github.com/Fenwick-Cooper/show-forecasts.git", rev = "for-mercury"}
jupyter = {version = "^1.0.0", optional = true}
jupyterlab = {version = "^4.2.3", optional = true}
psycopg2-binary = "^2.9.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
